---
# As deploy images could be managed external service (e.g. nginx),
# there is no need to setup the ownership

- name: Create HTTP root deploy folder
  file:
    path: "{{ ironic_deploy_http_root }}"
    group: "{{ ironic_group }}"
    mode: 0775
    state: directory


- block:
  - name: Check IPA Coreos ramdisk exists
    stat:
      path: "{{ ironic_deploy_http_root }}/{{ ironic_pxe_ipa_img_name }}"
    register: __stat_ipa_coreos_ramdisk
  - name: Downloading IPA Coreos ramdisk (~250 MB)
    get_url:
      # checksum: "{{ ironic_pxe_ipa_img_checksum }}"
      url: "{{ ironic_pxe_ipa_img_url }}"
      dest: "{{ ironic_deploy_http_root }}/{{ ironic_pxe_ipa_img_name }}"
    when: __stat_ipa_coreos_ramdisk.stat.exists == False

  - name: Check IPA Coreos kernel exists
    stat:
      path: "{{ ironic_deploy_http_root }}/{{ ironic_pxe_ipa_kernel_name }}"
    register: __stat_ipa_coreos_kernel
  - name: Downloading IPA Coreos kernel (~25 MB)
    get_url:
      # checksum: "{{ ironic_pxe_ipa_kernel_checksum }}"
      url: "{{ ironic_pxe_ipa_kernel_url }}"
      dest: "{{ ironic_deploy_http_root }}/{{ ironic_pxe_ipa_kernel_name }}"
    when: __stat_ipa_coreos_kernel.stat.exists == False

  - name: Change permissions
    file:
      path: "{{ item }}"
      group: "{{ ironic_group }}"
      mode: 0664
      state: file
    with_items:
      - "{{ ironic_deploy_http_root }}/{{ ironic_pxe_ipa_kernel_name }}"
      - "{{ ironic_deploy_http_root }}/{{ ironic_pxe_ipa_img_name }}"

  when: ironic_pxe_ipa_download


- block:
  - name: Check Tiny Core Ironic Python Agent ramdisk exists
    stat:
      path: "{{ ironic_deploy_http_root }}/{{ ironic_pxe_tinyipa_img_name }}"
    register: __stat_tinypa_ramdisk
  - name: Tiny Core Ironic Python Agent ramdisk (~40 MB)
    get_url:
      # checksum: "{{ ironic_pxe_tinyipa_img_checksum }}"
      url: "{{ ironic_pxe_tinyipa_img_url }}"
      dest: "{{ ironic_deploy_http_root }}/{{ ironic_pxe_tinyipa_img_name }}"
    when: __stat_tinypa_ramdisk.stat.exists == False

  - name: Check Tiny Core Ironic Python Agent kernel exists
    stat:
      path: "{{ ironic_deploy_http_root }}/{{ ironic_pxe_tinyipa_kernel_name }}"
    register: __stat_tinypa_kernel
  - name: Tiny Core Ironic Python Agent kernel (~4 MB)
    get_url:
      # checksum: "{{ ironic_pxe_tinyipa_kernel_checksum }}"
      url: "{{ ironic_pxe_tinyipa_kernel_url }}"
      dest: "{{ ironic_deploy_http_root }}/{{ ironic_pxe_tinyipa_kernel_name }}"
    when: __stat_tinypa_kernel.stat.exists == False

  - name: Change permissions
    file:
      path: "{{ item }}"
      group: "{{ ironic_group }}"
      mode: 0664
      state: file
    with_items:
      - "{{ ironic_deploy_http_root }}/{{ ironic_pxe_tinyipa_kernel_name }}"
      - "{{ ironic_deploy_http_root }}/{{ ironic_pxe_tinyipa_img_name }}"

  when: ironic_pxe_tinyipa_download

